name: CI to Snowflake via Workload Identity Federation
on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write   # <-- required for OIDC

jobs:
  run-snowflake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get OIDC token for Snowflake
        id: oidc
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken('snowflakecomputing.com');
            core.setOutput('id_token', token);

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Snowflake connector
        run: |
          python -m pip install --upgrade pip
          pip install "snowflake-connector-python>=3.15"

      - name: Query Snowflake with WIF
        env:
          OIDC_TOKEN: ${{ steps.oidc.outputs.id_token }}
        run: |
          python - <<'PY'
          import os, snowflake.connector
          conn = snowflake.connector.connect(
            account='TEDYZXG-INFINITYWORKSPARTNER'
            authenticator='WORKLOAD_IDENTITY',
            workload_identity_provider='OIDC',
            token=os.environ["OIDC_TOKEN"]
          )
          cur = conn.cursor()
          try:
              cur.execute("select current_user()")
              print(cur.fetchall())
          finally:
              cur.close()
              conn.close()
          PY
